### PR TITLE
Small updates for Management module.

### PR DESCRIPTION
**Pull request by isaacabraham**
Comments enhanced with defaults.
Underscores replaced with backtick names.

### CODE REVIEW

**Comment by palladin** [comment]
I'm not sure if APIs with backtick names are friendly for C# clients. I think it is best to avoid them for public apis.

**Comment by dsyme** [comment]
Yes I think that's right. Also we should think about having a powershell script that calls into MBrace.Azure (rather than using/assuming F# Interactive on the command line). 

So underscores should probably remain here.

**Comment by isaacabraham** [comment]
Good point. I'll re-push tomorrow (unless someone wants to modify it already)

**Comment by eiriktsarpalis** [comment]
Should we merge this? Also, what prohibits us from using enumerations in this context?

**Pull request merged**
