### PR TITLE
Retrieve app settings from environment variables for the standalone worker

### PR DESCRIPTION
**Pull request by bruinbrown**
Azure webjobs are the modern approach to hosting long running processes within Azure. Configuration in Azure webjobs is provided by environment variables prefixed with certain keywords. This PR introduces a dependency on @isaacabraham's Azure helper for configuration which loads the environment variables into the configuration manager, ensuring that the app settings are able to be read by Argu. This change only affects the StandaloneWorker project and would then allow it to be easily deployed as an Azure webjob.

### CODE REVIEW

**Comment by bruinbrown** [comment]
@eiriktsarpalis do you have any thoughts on what might be causing the build to fail? It looks like it's on vagabond related tests using FSI which hasn't changed at all with this PR

**Comment by eiriktsarpalis** [comment]
@bruinbrown looks like a binding redirect issue that's also affecting the master branch. I just pushed a fix there.

**Comment by eiriktsarpalis** [comment]
Could you try pulling the latest master? Tests are passing now.

**Comment by isaacabraham** [comment]
@eiriktsarpalis can you check that you're happy with this - it shouldn't have any impact on existing code; it'll only take effect if MBrace is hosted in the Azure App Service.

**Pull request merged**
