### PR TITLE
provisioning first cut

### PR DESCRIPTION
**Pull request by dsyme**
This adds a provisioning API to MBrace.Azure

When incorporated it will allow

    let pubSettingsFile = @"...Foo-credentials.publishsettings"
    
    Management.CreateCluster(pubSettingsFile,Regions.North_Europe)

There are various explicit options such as explicitly specifying the VM size etc.

There is one thing left to do after this: by default the compiled cloud service package will be drawn from 

    https://github.com/mbraceproject/MBrace.Azure/releases/download/VERSION/MBrace.Azure.CloudService-VMSIZE.cspkg

so we must adjust the FAKE Release build of MBrace.Azure to build a range of cloud service packages with different VM Size specifications and publish those as part of the release.

### CODE REVIEW

**Comment by dsyme** [comment]
With the latest update here's the necessary paket-powered load script (I've omitted the explicit CloudServicePackage argument that's currently required to show how the final script will look)

    let paket = System.IO.Path.Combine(__SOURCE_DIRECTORY__ , "paket.exe") in if not (System.IO.File.Exists paket) then let url = "https://github.com/fsprojects/Paket/releases/download/2.19.0/paket.exe" in use wc = new System.Net.WebClient() in let tmp = System.IO.Path.GetTempFileName() in wc.DownloadFile(url, tmp); System.IO.File.Move(tmp,paket);;

    #r "paket.exe"

    System.Environment.CurrentDirectory <- __SOURCE_DIRECTORY__
    Paket.Dependencies.Install "source https://nuget.org/api/v2 \n  nuget MBrace.Azure";;


    #load @"packages\MBrace.Azure\MBrace.Azure.fsx"
    open MBrace.Azure
    let pubSettingsFile = ...
    Management.CreateCluster(pubSettingsFile,Regions.North_Europe)
    Management.CreateCluster(pubSettingsFile,Regions.West_US,VMSize=VMSizes.A5,VMCount=24)

**Comment by palladin** [comment]
This line of work is very promising, MBrace Azure automation/scripting end-to-end!

**Comment by dsyme** [comment]
Merging after discussion with @palladin

**Comment by isaacabraham** [comment]
I'd like to see about exposing this sort of data towards a website as well - I think that even (as discussed with @dsyme) a self-hosted one would be a nice companion to this scripting model. This is how many other similar products e.g. Hadoop, Spark, Couchbase, RavenDB etc. etc..

**Comment by dsyme** [comment]
@isaacabraham Yes - including a suave single-script website might be the way to do this http://suave.io/paket.html.  You can deploy to Heroku or another place like this: http://suave.io/heroku.html

**Pull request merged**
