### PR TITLE
Auto delete service bus by default if the service bus is auto-generated.

### PR DESCRIPTION
**Pull request by isaacabraham**
Try again - moved to dedicated branch.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
I'm not sure if I agree with this PR. Basically this change will auto-remove the service bus account iff its name starts with 'mbrace', which is not necessarily an indication of it being auto-generated. In general though, I don't think it's a good idea to change the default behaviour of an optional parameter based on state. 

Another issue is that whereas a pair of storage & service bus accounts uniquely identify the state of an mbrace cluster, a specific deployment is a subset of that; indeed a cluster can consist of multiple or no deployments and this often changes with time. Deleting a deployment does not delete cluster state but deleting the service bus account does. The current policy of automatically reusing existing accounts is in tune with this idea.

**Comment by isaacabraham** [comment]
I've not heard of anyone using multiple MBrace Azure clusters on the same Service Bus account. Indeed, the default behaviour (at least, this is what I observed yesterday) is if you try to create a new MBrace cluster and there's already a cluster using an existing auto-generated service bus account, it will create a new one for you.

Lastly - absolutely right about the "starts with mbrace" - I took this from elsewhere in the codebase so it's something that we're already doing.

**Comment by isaacabraham** [comment]
Another idea I've had - perhaps just a WARN trace message on deletion that the service bus is still running and will incur costs? If we go down this approach we should provide an easy way to remove it.

**Comment by isaacabraham** [comment]
Closing due to inactivity.

**Pull request closed without merging**
