### PR TITLE
Worker status

### PR DESCRIPTION
**Pull request by krontogiannis**
This PR includes a few improvements regarding worker status:
* A `Status` property is added in `WorkerRef`. It's used to describe the following states:
    * Initializing. The worker service is starting.
    * Running. Worker successfully started.
    * Stopped. Worker service is stopped.
    * Faulted. Unhandled and possibly unrecoverable faults.
* WorkerRef now also contains the ConfigurationId instead of just a hash.
* Adjusted the default timespan used to check if a worker sends heartbeats to 10min.
* Heartbeat loop now logs any errors and increases the heartbeat interval in case of errors.
* If a worker gracefully exits, now status should be properly updated.
* GetWorker APIs now (optionally) show stopped or uninitialized workers.

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
I think it would make sense to add the property in IWorkerRef too.

**Comment by krontogiannis** [comment]
Probably, but I was thinking about adding some extra cases like `Idle` and specific steps of worker initialization. This should be generic enough, maybe sth like:
```fsharp
type Status =
| Initializing of step : string
| Running 
| Idle
| Stopped
| Faulted ex
```

**Comment by dsyme** [comment]
Out of curiosity, is a WorkerRef "Restart" or "Reboot" function plausible?

I ask based on experience today where a job was running very long, but my understanding is that it couldn't be killed using ``process.Kill()`` because it was running synchronous CPU work (I assume process.Kill is cooperative and won't kill blocking work). 

Killing the process using Kill() and rebooting the worker running the process seemed to me one path to get the process to actually die.

**Comment by eiriktsarpalis** [comment]
There is no restart capability as such. But you can force this using the programming model. Killing the process will force the instance to restart, so you can do the following:
```fsharp
let killWorker (w : IWorkerRef) = cloud {
    // delay for 1 sec in order for the success continuation to be fired before the process dies. 
    let exitAsync () = Async.Start(async { let! _ = Async.Sleep 1000 in return exit 1 })
    let! t = Cloud.StartAsCloudTask(cloud { exitAsync ()}, target = w)
    return ()
}

cluster.CreateProcess(killWorker w)
```

**Comment by dsyme** [comment]
But the worker is busy running another task, so it won't start this task, will it?

**Comment by eiriktsarpalis** [comment]
There is a `MaxConcurrentJobCount` value set in every worker. As long as it hasn't been reached it should execute it. AFAIK brisk sets that value to a multiple of the processor count.

**Comment by isaacabraham** [comment]
That's correct, we currently have it (IIRC) to 8 * core count.

**Comment by dsyme** [comment]
Ah, I see, thanks (for some reason I thought you had "core count" worker processes - many on each machine - rather than concurrent jobs in a single worker)

**Pull request merged**
